#
#   ____            _
#  |  _ \ _____   _(_)___  ___  ___
#  | |_) / _ \ \ / / / __|/ _ \/ __|
#  |  _ <  __/\ V /| \__ \  __/\__ \
#  |_| \_\___| \_/ |_|___/\___||___/
#
# Права доступа:
# revise.start - разрешает использование команд "/revise start", "/revise stop", "/revise finish" для управления проверками.
# revise.bypass.check - предоставляет защиту от автоматического вызова на проверку.
# revise.addtime - разрешает использование команды "/revise addtime" для добавления времени к текущей проверке.
# revise.bypass.addtime - позволяет обходить ограничение по времени проверки.
# revise.bypass.cooldown - позволяет обходить кулдауны на команды
# revise.checklogs - предоставляет доступ к команде "/revise logs" для просмотра логов проверок.
# revise.* - предоставляет полный доступ ко всем функциям плагина.
#
# Разработчик: https://t.me/bytesend

check:
  time:
    maximum: 3600 # Максимальное время проверки в секундах (без revise.bypass.addtime)
    period: 480 # Время по умолчанию для проверки в секундах
  teleport:
    toggle: true # Включает или выключает телепортацию при проверке
    TpToModerator: false # Телепортация к модератору при начале проверки
    tpToCoords: false # Телепортация по координатам при начале проверки
    tpInCoords:
      coords: # Координаты для телепортации
        x: -31.5
        y: 76.0
        z: 22.5
      world: world # Название мира для телепортации
      yaw: 0.0 # Угол поворота по горизонтали
      pitch: 0.0 # Угол поворота по вертикали

  suspect:
    move: false # Запрещает движение подозреваемого во время проверки
    interaction: false # Запрещает взаимодействие подозреваемого с миром во время проверки
    damage: false # Запрещает наносить урон подозреваемому во вермя проверки
    inventory:
      interaction: false # Запрещает взаимодействие с инвентарем во вермя проверки
      drop: false # Запрещяет дропать предметы
      click: false # Запрещяет клики в инвентаре
      moveitem: false # Запрещяет перемещять предметы
      pickupItem: true # Запрещяет подбирать предметы в инвентарь

  titles:
    toggle: false # Включает или выключает отображение заголовков и подзаголовков
    title: '' # Текст заголовка
    subTitle: '' # Текст подзаголовка

  actionbar:
    toggle: false # Включает или выключает отображение экшенбара
    text: '' # Текст экшенбара

  bossbar:
    toggle: true # Включает или выключает отображение босс-бара
    suspect:
      content: '&eУ вас осталось времени: &6%time%' # Содержимое босс-бара для подозреваемого
      stopTimeContent: '&cВы находитесь на проверки' # Сообщение босс-бара при остановке таймера
    inspector:
      content: '&eДо конца проверки осталось &6%time%' # Содержимое босс-бара для инспектора
    color: RED # Цвет босс-бара

  commands:
    toggle: false # Включает или выключает возможность использования команд во время проверки
    denyMessage: '&c> &fКоманды во время проверки отключены' # Сообщение подозреваемому при попытке использовать команду
    allowCommands:
      - reload # Список разрешенных команд
      -
  effects:
    toggle: false # Включает или выключает эффекты при проверке
    types:
      - BLINDNESS # Список эффектов, выдаются навсегда с максимальным уровнем

  chat:
    enable: false # Включает/выключает чат от плагина
    startMessage: '&fВы начали проверять игрока &9%suspect%' # Сообщение модератору при начале проверки
    copying:
      toggle: false # Включает или выключает возможность копирования сообщений
    hover:
      toggle: false # Включает или выключает ховер
      text: '&fНажми, чтобы скопировать сообщение' # Текст ховера

  prize:
    toggle: true # Включает или выключает выдачу приза после проверки
    item:
      hideFlags: true # Скрывает стандартные флаги предмета
      name: '&c[★] &eТрофей &6%player%' # Название предмета-приза
      lore: # Описание предмета-приза
        - '&c╔ &fПолучен от &cАдминистрации&f'
        - '&c╠ &fза честную игру на &6'
        - '&c╠ &fВедь после проверкки на читы'
        - '&c╠ &fВедь после проверкки на читы'
        - '&c╠ '
        - '&c╠ &fНик: &6%player%'
        - '&c╚ &fДата: &6%date%, %time%'

logging:
  toggle: true # Включает или выключает логирование результатов проверок
  message:
    - '&c╔ &fПроверяющий: &6%moderator%'
    - '&c╠ &fЧитер: &c%suspect%'
    - '&c╠ &fДата: &e%date%'
    - '&c╚ &fИсход - %result%'
  results:
    ban: '&c&lОбнаружены читы' # Сообщение при обнаружении читов
    verified: '&aПроверка пройдена' # Сообщение при успешной проверке
    endTime: '&eЗабанен за бездействие' # Сообщение при истечении времени проверки

system:
  autoBan:
    toggle: true # Включает или выключает автоматический бан при выходе игрока с сервера
    command: ban %suspect% Пункт 4.3 -s # Команда бана
    exitMessage: '&c> &fИгрок вышел во время проверки!' # Сообщение при выходе игрока во время проверки
    exitReasonMessage: '&fПричина выхода: %exit_reason%' # Сообщение с причиной выхода
  afk:
    toggle: true # Включает или выключает систему трэкинга AFK
    timeout: 900 # Время в секундах, после которого игрок считается AFK
    message: '&fИгрок &9%player% &fAFK, вы будите оповещены когда он выйдет с AFK' # Сообщение модератору если игрок в AFK
    left:
      message: '&fИгрок &9%player%&f вышел из AFK и выл бызван на проверку автоматически' # Сообщение при выходе из AFK
      runCheck: true # Автоматически запускает проверку при выходе из AFK

  cooldowns:
    commands:
      start: # Кулдаун для команды start
        period: 5 # -1 Для отключения
        message: У вас кулдаун еще %time% секунд
      logs:
        period: 5 # -1 Для отключения
        message: У вас кулдаун еще %time% секунд

database:
  strategy: SQLITE # Тип СУБД. Поддерживаемые СУБД: "SQLITE", "MYSQL" (MariaDB), "POSTGRESQL"
  host: localhost # Хост базы данных
  name: postgres # Имя базы данных
  port: 5432 # Порт базы данных
  username: postgres # Имя пользователя базы данных
  password: postgres # Пароль базы данных